application: verses
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /resources
  static_dir: static_folder

# Handles the cron task for one line lyric)
- url: /crons/oneline
  script: cronTasks.app

# the ending tag of main.app is .app instead of .py as
# app is declared as a global WSGI variable for
# handling requests
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
